add current.flow field & @environment fix
zillow/metaflow pull request #119
Opened 2021-09-14 02:12 UTC by talebzeghmi

2021-09-14 23:57 UTC, cloudw commented on metaflow/plugins/kfp/kfp.py
> +
Does this change accomplish the same as https://github.com/zillow/metaflow/blob/feature/kfp/metaflow/plugins/kfp/kfp_decorator.py#L91-L95 ? Let's just keep one of them.

Seeing your implementation here do we want to deprecate `kubernetes_vars` and use only `vars`? `container_op.container.add_env_variable(V1EnvVar(name, value))` seems to work in both cases right?

2021-09-15 00:01 UTC, cloudw requested changes
LGTM in general. Requesting change for potential duplicated handling of env var for `@environment` - I had a different fix in my PR that was just merged. See the other comment.

Could you please also provide a short description describing the purpose of this PR. I know your intention through private conversations but having a description will help when debugging in the future. The same message can easily be included in our release note as well.

2021-09-15 16:54 UTC, hsezhiyan approved these changes

2021-09-15 17:32 UTC, cloudw approved these changes

2021-09-15 18:37 UTC, merged