AIP-5330 set default retry policy="Always" (even on PodDeletion)
zillow/metaflow pull request #134
Opened 2021-11-04 02:09 UTC by talebzeghmi

* https://github.com/kubeflow/pipelines/issues/4333
* https://argoproj.github.io/argo-workflows/tolerating-pod-deletion/

The Argo default retry policy does not handle pod deletion events.

2021-11-04 18:50 UTC, cloudw requested changes
LGTM. A minor issue mentioned.

2021-11-04 18:50 UTC, cloudw commented on metaflow/plugins/kfp/tests/flows/failure_flow.py
> +    start_sleep = Parameter("start_sleep", default=60)
I don't see this parameter used elsewhere.

2021-11-05 17:53 UTC, cloudw approved these changes

2021-11-06 21:42 UTC, hsezhiyan approved these changes

2021-11-07 06:44 UTC, merged