Allow memory configuration in s3 sensor
zillow/metaflow pull request #186
Opened 2022-08-15 17:50 UTC by cloudw

Some project may have memory usage exceeding 200M default used in s3 sensor. Allowing this memory limit and request to be increased.

2022-08-15 18:37 UTC, talebzeghmi requested changes

2022-08-15 18:37 UTC, talebzeghmi commented on metaflow/plugins/kfp/kfp.py
> +        KubeflowPipelines._set_minimal_container_resources(s3_sensor_op, memory)
It'd be good to document what kind of values `memory` can take.

2022-08-15 22:07 UTC, cloudw commented
Actually fixed the customer project pipeline without this PR. It turns out to be another data issue.

Closing this PR for now.

2023-05-19 17:24 UTC, cloudw commented
Closing again as no progress was made here for half a year.

2023-05-19 17:24 UTC, closed without merging